const mongoose = require('mongoose');

const gitHubRepositorySchema = new mongoose.Schema({
  projectId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Project',
    required: true,
    unique: true,
    index: true
  },
  owner: {
    type: String,
    required: true,
    trim: true
  },
  repository: {
    type: String,
    required: true,
    trim: true
  },
  defaultBranch: {
    type: String,
    default: 'main',
    trim: true
  },
  repositoryUrl: {
    type: String,
    trim: true
  },
  connectedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  connectedAt: {
    type: Date,
    default: Date.now
  },
  lastSyncedAt: {
    type: Date,
    default: null
  },
  connectionStatus: {
    type: String,
    enum: ['Connected', 'Disconnected', 'Error', 'Syncing'],
    default: 'Connected'
  },
  repositoryVisibility: {
    type: String,
    enum: ['public', 'private', 'unknown'],
    default: 'unknown'
  },
  // Cached GitHub data (updated on sync)
  cachedData: {
    // Repository info
    repoInfo: { type: mongoose.Schema.Types.Mixed, default: null },
    // List of commits (recent)
    commits: { type: [mongoose.Schema.Types.Mixed], default: [] },
    // Pull requests
    pullRequests: { type: [mongoose.Schema.Types.Mixed], default: [] },
    // Issues
    issues: { type: [mongoose.Schema.Types.Mixed], default: [] },
    // Branches
    branches: { type: [mongoose.Schema.Types.Mixed], default: [] },
    // Contributors
    contributors: { type: [mongoose.Schema.Types.Mixed], default: [] },
    // Languages
    languages: { type: mongoose.Schema.Types.Mixed, default: {} },
    // Releases
    releases: { type: [mongoose.Schema.Types.Mixed], default: [] },
    // Workflows (GitHub Actions)
    workflows: { type: [mongoose.Schema.Types.Mixed], default: [] },
    // README status
    hasReadme: { type: Boolean, default: false },
    // Tree (top-level files)
    tree: { type: [mongoose.Schema.Types.Mixed], default: [] }
  },
  // AI-generated analysis of the repository
  aiAnalysis: {
    type: mongoose.Schema.Types.Mixed,
    default: null
  },
  aiAnalysisGeneratedAt: {
    type: Date,
    default: null
  },
  // Commit summary generated by AI
  commitSummary: {
    type: mongoose.Schema.Types.Mixed,
    default: null
  },
  commitSummaryGeneratedAt: {
    type: Date,
    default: null
  },
  // Repository health score
  healthStatus: {
    type: String,
    enum: ['Excellent', 'Healthy', 'Needs Attention', 'Critical', 'Unknown'],
    default: 'Unknown'
  },
  healthScore: {
    type: Number,
    default: 0,
    min: 0,
    max: 100
  }
}, {
  timestamps: true
});

module.exports = mongoose.model('GitHubRepository', gitHubRepositorySchema);
